### ISSUE TITLE
Legacy stuff

### ISSUE THREAD

**Issue by cojoj** [JohnSundell/SwiftScripting#3]
This is a new way of how we can use Swift for scripting, and the current list contains only maintained and relatively new tools... But there are also old ones. @JohnSundell, do you think they should be added, mentioned, marked as deprecated?

For example, take a look at https://github.com/owensd/apous

---
I know you're making some presentations right now about **scripting in Swift**, so maybe it'd be nice to also have a section with some learning resources? Maybe a subdirectory with something like that?

**Comment by JohnSundell** [comment]
@cojoj Thanks for your suggestions! Since this is a brand new repo, I don't think it makes sense to add any legacy stuff to it. I'd rather keep it streamlined with the most modern/updated tools and current standards. Makes it easier to digest and to maintain it.

I'd love to add learning resources. If you have any already that you think would be valuable, then feel free to open a PR! I'll make sure to add links to my videos once they are available 👍

**Comment by JohnSundell** [comment]
@cojoj OK if I close this?
